const t = {
    en: { title: 'Club Management System', user: 'Your username:', userP: 'Enter your username', pass: 'Your password:', passP: 'Type the password', code: 'Complete the code:', codeP: 'CODE DISPLAYED ABOVE', submit: 'To access CMS', account: 'Request An Account', privacy: 'Privacy Policy', forgot: 'Forgot password?', required: 'Complete all fields.', short: 'The password must be at least 6 characters.', wrong: 'Incorrect verification code.', ok: 'Validation completed. Redirecting to the official CMS...' },
    pt: { title: 'Sistema de Gestão de Clubes', user: 'Seu usuário:', userP: 'Digite seu usuário', pass: 'Sua senha:', passP: 'Digite sua senha', code: 'Complete o código:', codeP: 'CÓDIGO EXIBIDO ACIMA', submit: 'Acessar o SGC', account: 'Solicitar uma conta', privacy: 'Política de Privacidade', forgot: 'Esqueceu a senha?', required: 'Preencha todos os campos.', short: 'A senha deve ter pelo menos 6 caracteres.', wrong: 'Código de verificação incorreto.', ok: 'Validação concluída. Redirecionando ao SGC oficial...' },
    es: { title: 'Sistema de Gestión de Clubes', user: 'Su usuario:', userP: 'Ingrese su usuario', pass: 'Su contraseña:', passP: 'Ingrese su contraseña', code: 'Complete el código:', codeP: 'CÓDIGO MOSTRADO ARRIBA', submit: 'Acceder al SGC', account: 'Solicitar una cuenta', privacy: 'Política de Privacidad', forgot: '¿Olvidó su contraseña?', required: 'Complete todos los campos.', short: 'La contraseña debe tener al menos 6 caracteres.', wrong: 'Código de verificación incorrecto.', ok: 'Validación completada. Redirigiendo al SGC oficial...' }
};
let lang = 'en', current = '';
function captcha() { current = Math.random().toString(36).slice(2, 6).toUpperCase(); document.querySelector('#captcha').textContent = current }
function setLang(l) { lang = l; const x = t[l]; title.textContent = x.title; userLabel.textContent = x.user; login.placeholder = x.userP; passLabel.textContent = x.pass; senha.placeholder = x.passP; codeLabel.textContent = x.code; codigo.placeholder = x.codeP; submitText.textContent = x.submit; accountText.textContent = x.account; privacyText.textContent = x.privacy; forgotText.textContent = x.forgot; accountText.href = 'https://sg.sdasystems.org/cms/paises.php?lang=' + (l === 'pt' ? 'pt_br' : l === 'es' ? 'esp' : 'en'); forgotText.href = 'https://sg.sdasystems.org/cms/senha.php?lang=' + (l === 'pt' ? 'pt_br' : l === 'es' ? 'esp' : 'en') }
document.querySelectorAll('[data-lang]').forEach(i => i.onclick = () => setLang(i.dataset.lang));
document.querySelector('#captcha').onclick = captcha;
loginForm.onsubmit = e => { e.preventDefault(); msg.textContent = ''; if (!login.value.trim() || !senha.value || !codigo.value.trim()) return msg.textContent = t[lang].required; if (senha.value.length < 6) return msg.textContent = t[lang].short; if (codigo.value.trim().toUpperCase() !== current) return msg.textContent = t[lang].wrong; msg.textContent = t[lang].ok; setTimeout(() => location.href = 'https://sg.sdasystems.org/cms/login.php?lang=' + (lang === 'pt' ? 'pt_br' : lang === 'es' ? 'esp' : 'en'), 900) };
captcha(); setLang('en');